"""empty message

Revision ID: 63008bf8a34a
Revises: c77465b137e1
Create Date: 2022-05-22 21:54:56.380584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63008bf8a34a'
down_revision = 'c77465b137e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('website', sa.String(length=120), nullable=True))
    op.add_column('venues', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('venues', sa.Column('seeking_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'seeking_description')
    op.drop_column('venues', 'seeking_talent')
    op.drop_column('venues', 'website')
    # ### end Alembic commands ###
