"""empty message

Revision ID: 63eecaa9a318
Revises: 1555af903386
Create Date: 2022-05-23 16:52:06.045369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63eecaa9a318'
down_revision = '1555af903386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'upcoming')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('upcoming', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
